<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class BeverageProductsSeeder extends Seeder
{
    public function run()
    {
        // Lấy các danh mục
        $categories = Category::pluck('id', 'name')->toArray();
        
        $products = [
            // Nước ngọt có ga (10 sản phẩm)
            [
                'name' => 'Coca Cola 330ml',
                'description' => 'Nước ngọt có ga Coca Cola hương vị truyền thống',
                'price' => 12000,
                'quantity' => 500,
                'brand' => 'Coca Cola',
                'flavor' => 'Cola',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, caffeine, hương liệu tự nhiên',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Pepsi 330ml',
                'description' => 'Nước ngọt có ga Pepsi với hương vị độc đáo',
                'price' => 12000,
                'quantity' => 450,
                'brand' => 'Pepsi',
                'flavor' => 'Cola',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, caffeine, hương liệu',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Sprite 330ml',
                'description' => 'Nước ngọt có ga vị chanh tươi mát',
                'price' => 12000,
                'quantity' => 400,
                'brand' => 'Coca Cola',
                'flavor' => 'Chanh',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, hương chanh tự nhiên',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => '7UP 330ml',
                'description' => 'Nước ngọt có ga vị chanh bưởi',
                'price' => 12000,
                'quantity' => 350,
                'brand' => 'PepsiCo',
                'flavor' => 'Chanh bưởi',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, hương chanh bưởi',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Fanta Cam 330ml',
                'description' => 'Nước ngọt có ga hương cam tươi',
                'price' => 12000,
                'quantity' => 300,
                'brand' => 'Coca Cola',
                'flavor' => 'Cam',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, hương cam tự nhiên',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Mirinda Cam 330ml',
                'description' => 'Nước ngọt có ga hương cam sảng khoái',
                'price' => 12000,
                'quantity' => 280,
                'brand' => 'PepsiCo',
                'flavor' => 'Cam',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, hương cam',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Sting Dâu 330ml',
                'description' => 'Nước tăng lực có ga hương dâu',
                'price' => 15000,
                'quantity' => 200,
                'brand' => 'PepsiCo',
                'flavor' => 'Dâu',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, caffeine, taurine, hương dâu',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Schweppes Soda 330ml',
                'description' => 'Nước soda có ga nguyên chất',
                'price' => 18000,
                'quantity' => 150,
                'brand' => 'Schweppes',
                'flavor' => 'Soda',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, CO2, muối khoáng',
                'origin_country' => 'Thái Lan',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Mountain Dew 330ml',
                'description' => 'Nước ngọt có ga hương chanh độc đáo',
                'price' => 15000,
                'quantity' => 180,
                'brand' => 'PepsiCo',
                'flavor' => 'Chanh',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, caffeine, hương chanh',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],
            [
                'name' => 'Revive Isotonic 330ml',
                'description' => 'Nước bù khoáng có ga',
                'price' => 16000,
                'quantity' => 120,
                'brand' => 'Coca Cola',
                'flavor' => 'Chanh muối',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, CO2, muối khoáng, vitamin',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt có ga'] ?? 1
            ],

            // Nước ngọt không ga (8 sản phẩm)
            [
                'name' => 'Trà Xanh Không Độ 500ml',
                'description' => 'Trà xanh không đường, không ga',
                'price' => 10000,
                'quantity' => 300,
                'brand' => 'Trà Xanh Không Độ',
                'flavor' => 'Trà xanh',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, lá trà xanh, vitamin C',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Olong Tea Plus 455ml',
                'description' => 'Trà ô long không ga với hương vị đậm đà',
                'price' => 12000,
                'quantity' => 250,
                'brand' => 'Olong Tea Plus',
                'flavor' => 'Trà ô long',
                'volume' => '455ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, lá trà ô long, đường, vitamin',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Lipton Ice Tea Đào 500ml',
                'description' => 'Trà đá hương đào không ga',
                'price' => 13000,
                'quantity' => 200,
                'brand' => 'Lipton',
                'flavor' => 'Đào',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, trà đen, đường, hương đào tự nhiên',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Fuze Tea Chanh 500ml',
                'description' => 'Trà chanh không ga tươi mát',
                'price' => 14000,
                'quantity' => 180,
                'brand' => 'Fuze Tea',
                'flavor' => 'Chanh',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, trà đen, đường, nước cốt chanh',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Nestea Chanh 500ml',
                'description' => 'Trà chanh không ga của Nestlé',
                'price' => 13000,
                'quantity' => 220,
                'brand' => 'Nestea',
                'flavor' => 'Chanh',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, trà, đường, hương chanh',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Aquarius Chanh Muối 500ml',
                'description' => 'Nước bù khoáng không ga vị chanh muối',
                'price' => 15000,
                'quantity' => 160,
                'brand' => 'Aquarius',
                'flavor' => 'Chanh muối',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, đường, muối khoáng, hương chanh',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Pokka Trà Xanh 500ml',
                'description' => 'Trà xanh Nhật Bản không ga',
                'price' => 16000,
                'quantity' => 140,
                'brand' => 'Pokka',
                'flavor' => 'Trà xanh',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, lá trà xanh Nhật Bản, đường',
                'origin_country' => 'Singapore',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],
            [
                'name' => 'Vita Soy Đậu Nành 500ml',
                'description' => 'Sữa đậu nành không ga',
                'price' => 18000,
                'quantity' => 100,
                'brand' => 'Vita Soy',
                'flavor' => 'Đậu nành',
                'volume' => '500ml',
                'packaging_type' => 'Hộp',
                'is_carbonated' => false,
                'ingredients' => 'Nước, đậu nành, đường, muối',
                'origin_country' => 'Hong Kong',
                'category_id' => $categories['Nước ngọt không ga'] ?? 2
            ],

            // Nước trái cây (8 sản phẩm)
            [
                'name' => 'Tropicana Cam 1L',
                'description' => 'Nước cam ép 100% từ trái cây tươi',
                'price' => 35000,
                'quantity' => 80,
                'brand' => 'Tropicana',
                'flavor' => 'Cam',
                'volume' => '1L',
                'packaging_type' => 'Hộp',
                'is_carbonated' => false,
                'ingredients' => '100% nước cam ép, vitamin C',
                'origin_country' => 'Thái Lan',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'Minute Maid Cam 330ml',
                'description' => 'Nước cam có thịt từ Coca Cola',
                'price' => 15000,
                'quantity' => 150,
                'brand' => 'Minute Maid',
                'flavor' => 'Cam',
                'volume' => '330ml',
                'packaging_type' => 'Hộp',
                'is_carbonated' => false,
                'ingredients' => 'Nước cam ép, thịt cam, đường, vitamin C',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'TH True Juice Cam 1L',
                'description' => 'Nước cam ép tươi không đường',
                'price' => 45000,
                'quantity' => 60,
                'brand' => 'TH True Juice',
                'flavor' => 'Cam',
                'volume' => '1L',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => '100% nước cam ép tươi',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'Twister Cam Chanh 390ml',
                'description' => 'Nước trái cây hỗn hợp cam chanh',
                'price' => 12000,
                'quantity' => 200,
                'brand' => 'Twister',
                'flavor' => 'Cam chanh',
                'volume' => '390ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước cam, nước chanh, đường, vitamin C',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'Malee Xoài 1L',
                'description' => 'Nước xoài nguyên chất từ Thái Lan',
                'price' => 40000,
                'quantity' => 70,
                'brand' => 'Malee',
                'flavor' => 'Xoài',
                'volume' => '1L',
                'packaging_type' => 'Hộp',
                'is_carbonated' => false,
                'ingredients' => 'Nước xoài ép, đường, acid citric',
                'origin_country' => 'Thái Lan',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'Tipco Dứa 1L',
                'description' => 'Nước dứa 100% tự nhiên',
                'price' => 38000,
                'quantity' => 65,
                'brand' => 'Tipco',
                'flavor' => 'Dứa',
                'volume' => '1L',
                'packaging_type' => 'Hộp',
                'is_carbonated' => false,
                'ingredients' => '100% nước dứa ép, vitamin C',
                'origin_country' => 'Thái Lan',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'Real Grape 500ml',
                'description' => 'Nước nho đỏ nguyên chất',
                'price' => 25000,
                'quantity' => 90,
                'brand' => 'Real',
                'flavor' => 'Nho',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước nho ép, đường, acid citric',
                'origin_country' => 'Hàn Quốc',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],
            [
                'name' => 'Sunquick Chanh Dây 840ml',
                'description' => 'Syrup chanh dây pha chế',
                'price' => 32000,
                'quantity' => 50,
                'brand' => 'Sunquick',
                'flavor' => 'Chanh dây',
                'volume' => '840ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước chanh dây, đường, chất bảo quản',
                'origin_country' => 'Malaysia',
                'category_id' => $categories['Nước trái cây'] ?? 3
            ],

            // Nước khoáng (6 sản phẩm)
            [
                'name' => 'Aquafina 500ml',
                'description' => 'Nước tinh khiết Aquafina',
                'price' => 8000,
                'quantity' => 1000,
                'brand' => 'Aquafina',
                'flavor' => 'Nguyên chất',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước tinh khiết',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước khoáng'] ?? 4
            ],
            [
                'name' => 'Lavie 500ml',
                'description' => 'Nước khoáng tự nhiên Lavie',
                'price' => 7000,
                'quantity' => 800,
                'brand' => 'Lavie',
                'flavor' => 'Nguyên chất',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước khoáng tự nhiên',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước khoáng'] ?? 4
            ],
            [
                'name' => 'Vinh Hao 500ml',
                'description' => 'Nước khoáng thiên nhiên Vinh Hao',
                'price' => 6000,
                'quantity' => 600,
                'brand' => 'Vinh Hao',
                'flavor' => 'Nguyên chất',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước khoáng thiên nhiên',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước khoáng'] ?? 4
            ],
            [
                'name' => 'Evian 500ml',
                'description' => 'Nước khoáng tự nhiên từ Alps',
                'price' => 25000,
                'quantity' => 100,
                'brand' => 'Evian',
                'flavor' => 'Nguyên chất',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước khoáng tự nhiên từ Alps',
                'origin_country' => 'Pháp',
                'category_id' => $categories['Nước khoáng'] ?? 4
            ],
            [
                'name' => 'Perrier 330ml',
                'description' => 'Nước khoáng có ga tự nhiên',
                'price' => 30000,
                'quantity' => 80,
                'brand' => 'Perrier',
                'flavor' => 'Nguyên chất',
                'volume' => '330ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => true,
                'ingredients' => 'Nước khoáng có ga tự nhiên',
                'origin_country' => 'Pháp',
                'category_id' => $categories['Nước khoáng'] ?? 4
            ],
            [
                'name' => 'San Pellegrino 500ml',
                'description' => 'Nước khoáng có ga từ Ý',
                'price' => 35000,
                'quantity' => 60,
                'brand' => 'San Pellegrino',
                'flavor' => 'Nguyên chất',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => true,
                'ingredients' => 'Nước khoáng có ga tự nhiên',
                'origin_country' => 'Ý',
                'category_id' => $categories['Nước khoáng'] ?? 4
            ],

            // Nước tăng lực (6 sản phẩm)
            [
                'name' => 'Red Bull 250ml',
                'description' => 'Nước tăng lực Red Bull nguyên bản',
                'price' => 25000,
                'quantity' => 300,
                'brand' => 'Red Bull',
                'flavor' => 'Nguyên bản',
                'volume' => '250ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, caffeine, taurine, vitamin B',
                'origin_country' => 'Thái Lan',
                'category_id' => $categories['Nước tăng lực'] ?? 5
            ],
            [
                'name' => 'Monster Energy 355ml',
                'description' => 'Nước tăng lực Monster Energy',
                'price' => 35000,
                'quantity' => 200,
                'brand' => 'Monster',
                'flavor' => 'Nguyên bản',
                'volume' => '355ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, caffeine, taurine, ginseng',
                'origin_country' => 'Mỹ',
                'category_id' => $categories['Nước tăng lực'] ?? 5
            ],
            [
                'name' => 'Sting Vàng 330ml',
                'description' => 'Nước tăng lực Sting hương vị truyền thống',
                'price' => 15000,
                'quantity' => 400,
                'brand' => 'Sting',
                'flavor' => 'Vàng',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, caffeine, taurine, vitamin',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước tăng lực'] ?? 5
            ],
            [
                'name' => 'Number 1 Energy 330ml',
                'description' => 'Nước tăng lực Number 1',
                'price' => 12000,
                'quantity' => 350,
                'brand' => 'Number 1',
                'flavor' => 'Nguyên bản',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, caffeine, taurine',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước tăng lực'] ?? 5
            ],
            [
                'name' => 'Warrior 330ml',
                'description' => 'Nước tăng lực Warrior',
                'price' => 13000,
                'quantity' => 300,
                'brand' => 'Warrior',
                'flavor' => 'Nguyên bản',
                'volume' => '330ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, caffeine, taurine, vitamin B',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước tăng lực'] ?? 5
            ],
            [
                'name' => 'Rockstar Energy 500ml',
                'description' => 'Nước tăng lực Rockstar',
                'price' => 40000,
                'quantity' => 150,
                'brand' => 'Rockstar',
                'flavor' => 'Nguyên bản',
                'volume' => '500ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => true,
                'ingredients' => 'Nước, đường, caffeine, taurine, ginseng, guarana',
                'origin_country' => 'Mỹ',
                'category_id' => $categories['Nước tăng lực'] ?? 5
            ],

            // Trà và cà phê (6 sản phẩm)
            [
                'name' => 'Highlands Coffee Đen Đá 235ml',
                'description' => 'Cà phê đen đá truyền thống Việt Nam',
                'price' => 20000,
                'quantity' => 200,
                'brand' => 'Highlands Coffee',
                'flavor' => 'Cà phê đen',
                'volume' => '235ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => false,
                'ingredients' => 'Nước, cà phê robusta, đường',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Trà và cà phê'] ?? 6
            ],
            [
                'name' => 'Trung Nguyên G7 240ml',
                'description' => 'Cà phê sữa G7 3in1',
                'price' => 18000,
                'quantity' => 250,
                'brand' => 'Trung Nguyên',
                'flavor' => 'Cà phê sữa',
                'volume' => '240ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => false,
                'ingredients' => 'Nước, cà phê, sữa, đường',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Trà và cà phê'] ?? 6
            ],
            [
                'name' => 'UCC Coffee Đen 275ml',
                'description' => 'Cà phê đen Nhật Bản UCC',
                'price' => 22000,
                'quantity' => 180,
                'brand' => 'UCC',
                'flavor' => 'Cà phê đen',
                'volume' => '275ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => false,
                'ingredients' => 'Nước, cà phê arabica, đường',
                'origin_country' => 'Nhật Bản',
                'category_id' => $categories['Trà và cà phê'] ?? 6
            ],
            [
                'name' => 'Nescafe Latte 280ml',
                'description' => 'Cà phê sữa Nescafe',
                'price' => 19000,
                'quantity' => 220,
                'brand' => 'Nescafe',
                'flavor' => 'Latte',
                'volume' => '280ml',
                'packaging_type' => 'Lon',
                'is_carbonated' => false,
                'ingredients' => 'Nước, cà phê, sữa, đường',
                'origin_country' => 'Thái Lan',
                'category_id' => $categories['Trà và cà phê'] ?? 6
            ],
            [
                'name' => 'Trà Ô Long TEA+ 500ml',
                'description' => 'Trà ô long không đường',
                'price' => 15000,
                'quantity' => 300,
                'brand' => 'TEA+',
                'flavor' => 'Ô long',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, lá trà ô long, vitamin C',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Trà và cà phê'] ?? 6
            ],
            [
                'name' => 'Matcha Latte 350ml',
                'description' => 'Trà xanh matcha sữa',
                'price' => 25000,
                'quantity' => 150,
                'brand' => 'Matcha House',
                'flavor' => 'Matcha',
                'volume' => '350ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, bột matcha, sữa, đường',
                'origin_country' => 'Nhật Bản',
                'category_id' => $categories['Trà và cà phê'] ?? 6
            ],

            // Nước uống thể thao (6 sản phẩm)
            [
                'name' => 'Pocari Sweat 500ml',
                'description' => 'Nước bù ion điện giải Pocari Sweat',
                'price' => 20000,
                'quantity' => 300,
                'brand' => 'Pocari Sweat',
                'flavor' => 'Ion',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, đường, muối khoáng, ion điện giải',
                'origin_country' => 'Nhật Bản',
                'category_id' => $categories['Nước uống thể thao'] ?? 7
            ],
            [
                'name' => 'Gatorade Cam 500ml',
                'description' => 'Nước thể thao Gatorade hương cam',
                'price' => 22000,
                'quantity' => 250,
                'brand' => 'Gatorade',
                'flavor' => 'Cam',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, đường, muối khoáng, hương cam',
                'origin_country' => 'Mỹ',
                'category_id' => $categories['Nước uống thể thao'] ?? 7
            ],
            [
                'name' => 'Powerade Xanh 500ml',
                'description' => 'Nước thể thao Powerade',
                'price' => 20000,
                'quantity' => 200,
                'brand' => 'Powerade',
                'flavor' => 'Mountain Berry',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, đường, muối khoáng, vitamin B',
                'origin_country' => 'Mỹ',
                'category_id' => $categories['Nước uống thể thao'] ?? 7
            ],
            [
                'name' => 'Aquarius Zero 500ml',
                'description' => 'Nước thể thao không đường',
                'price' => 18000,
                'quantity' => 180,
                'brand' => 'Aquarius',
                'flavor' => 'Zero',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, muối khoáng, chất tạo ngọt',
                'origin_country' => 'Nhật Bản',
                'category_id' => $categories['Nước uống thể thao'] ?? 7
            ],
            [
                'name' => 'Mizone Chanh 500ml',
                'description' => 'Nước vitamin Mizone hương chanh',
                'price' => 16000,
                'quantity' => 220,
                'brand' => 'Mizone',
                'flavor' => 'Chanh',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, vitamin C, B3, B6, hương chanh',
                'origin_country' => 'Trung Quốc',
                'category_id' => $categories['Nước uống thể thao'] ?? 7
            ],
            [
                'name' => 'H2O Sport 500ml',
                'description' => 'Nước thể thao H2O',
                'price' => 15000,
                'quantity' => 160,
                'brand' => 'H2O',
                'flavor' => 'Chanh muối',
                'volume' => '500ml',
                'packaging_type' => 'Chai',
                'is_carbonated' => false,
                'ingredients' => 'Nước, muối khoáng, hương chanh',
                'origin_country' => 'Việt Nam',
                'category_id' => $categories['Nước uống thể thao'] ?? 7
            ]
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}